-- GENERATED BY scripts/build-migration-audit.mjs - DO NOT EDIT BY HAND.
-- Regenerate with `npm run db:audit`. The unit suite fails when this file and
-- supabase/migrations/ disagree.
--
-- Which of supabase/migrations/ has this database actually got?
--
-- Read-only. Runs in the Supabase SQL editor against any project, including one
-- that was never built through the CLI and therefore has no
-- `supabase_migrations.schema_migrations` history for `npm run db:status` to
-- read. It asks the schema what is there rather than asking the CLI what it was
-- told, which is the only question that can be answered on this project today
-- (CLAUDE.md, "Database Migrations").
--
-- Each row names one migration and the object that migration is the only thing
-- to create. `present = false` means that migration has not been applied - or was
-- applied and then partially rolled back, which looks the same from here and
-- wants the same investigation.
--
-- WHAT THIS CANNOT TELL YOU: whether PostgREST can SEE what the schema has.
-- A stale schema cache leaves every row below `true` while the Data API answers
-- `PGRST202 Could not find the function ... in the schema cache` - byte-identical
-- to the answer it gives when the function is genuinely absent. If the rows are
-- all `true` and riders still get that error, the cache is the cause: reload it
-- with `notify pgrst, 'reload schema';` (see the runbook entry this ships with).
with expected(ordinality, migration, object_kind, object_name, present) as (values
  (1, '20260223000000_init_baseline_schema', 'table',
      'public.sessions',
      to_regclass('public.sessions') is not null),
  (2, '20260224000000_add_sag_entries', 'table',
      'public.sag_entries',
      to_regclass('public.sag_entries') is not null),
  (3, '20260224000100_add_stripe_profile_fields', 'column',
      'public.profiles.stripe_customer_id',
      exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='profiles'
                and column_name='stripe_customer_id')),
  (4, '20260228000200_add_session_module_metadata', 'column',
      'public.sessions.enabled_modules',
      exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='sessions'
                and column_name='enabled_modules')),
  (5, '20260420000300_add_ai_requests', 'table',
      'public.ai_requests',
      to_regclass('public.ai_requests') is not null),
  (6, '20260422000400_add_adaptive_race_engineer', 'table',
      'public.ai_recommendations',
      to_regclass('public.ai_recommendations') is not null),
  (7, '20260424000500_add_ai_request_observability', 'index',
      'ai_requests_user_fingerprint_created_idx',
      to_regclass('public.ai_requests_user_fingerprint_created_idx') is not null),
  (8, '20260626000600_add_vehicle_baselines', 'table',
      'public.vehicle_baselines',
      to_regclass('public.vehicle_baselines') is not null),
  (9, '20260705000700_add_session_changes', 'table',
      'public.session_changes',
      to_regclass('public.session_changes') is not null),
  -- The reported defect. Nine arguments, in the order the route sends them.
  (10, '20260716000800_add_session_outcomes', 'function',
      'public.save_session_outcome(uuid,uuid,uuid,uuid,text,smallint,text[],text,smallint)',
      to_regprocedure('public.save_session_outcome(uuid,uuid,uuid,uuid,text,smallint,text[],text,smallint)') is not null),
  (11, '20260717000900_add_session_laps', 'table',
      'public.session_laps',
      to_regclass('public.session_laps') is not null),
  (12, '20260718001000_add_beta_foundation', 'table',
      'public.beta_invites',
      to_regclass('public.beta_invites') is not null),
  -- Grants, not objects, so it takes two halves. The insert on sessions is one
  -- this migration is the only thing in the repository to make, and without it
  -- the Data API answers `permission denied for table` on a project created
  -- today - one built before Supabase turned off `auto_expose_new_tables` gets
  -- it from the legacy defaults instead. The revoke is the other half:
  -- `authenticated` must NOT hold update on profiles, because RLS picks the row
  -- and cannot restrict the column, so that privilege is a rider setting their
  -- own `tier`. Testing only the revoke would read `present` on a database that
  -- never granted anything at all.
  --
  -- The CASE is load-bearing rather than style. `has_table_privilege` RAISES on
  -- a table that does not exist, and Postgres does not promise to short-circuit
  -- AND - the docs send you to CASE when evaluation order matters. Without it,
  -- a database missing the baseline aborts this whole query on this row instead
  -- of printing the MISSING rows the operator came here to read, which is
  -- exactly the state the first row exists to report.
  (13, '20260719001100_grant_data_api_access', 'grant',
      'authenticated has insert on public.sessions and NO update on public.profiles',
      case when to_regclass('public.sessions') is null
             or to_regclass('public.profiles') is null then false
           else has_table_privilege('authenticated', 'public.sessions', 'insert')
                and not has_table_privilege('authenticated', 'public.profiles', 'update')
      end),
  (14, '20260816001200_add_profile_on_auth_user_created', 'trigger',
      'on_auth_user_created on auth.users',
      exists (select 1 from pg_trigger
              where tgname='on_auth_user_created'
                and tgrelid='auth.users'::regclass
                and not tgisinternal)),
  (15, '20260824001300_add_vehicle_photos_storage_policies', 'policy',
      'vehicle-photos: insert own (storage.objects)',
      exists (select 1 from pg_policies
              where schemaname='storage' and tablename='objects'
                and policyname='vehicle-photos: insert own')),
  -- 20260901001400 shipped replace_session_laps(...,integer) and 20260903001500
  -- replaced it with (...,jsonb), dropping both earlier signatures. So the
  -- integer form present means 1400 applied and 1500 did not; the jsonb form
  -- present means 1500 applied, which implies 1400 did too.
  (16, '20260901001400_guard_replace_session_laps_against_stale_reads', 'function',
      'public.replace_session_laps(uuid,uuid,jsonb,integer) OR its 1500 replacement',
      to_regprocedure('public.replace_session_laps(uuid,uuid,jsonb,integer)') is not null
      or to_regprocedure('public.replace_session_laps(uuid,uuid,jsonb,jsonb)') is not null),
  (17, '20260903001500_replace_session_laps_compares_lap_content', 'function',
      'public.session_laps_identity(jsonb)',
      to_regprocedure('public.replace_session_laps(uuid,uuid,jsonb,jsonb)') is not null
      and to_regprocedure('public.session_laps_identity(jsonb)') is not null),
  -- The seeded rows themselves: select count(*) from public.tracks where slug is not null (50).
  (18, '20260916001600_seed_north_america_tracks', 'table',
      'public.track_aliases',
      to_regclass('public.track_aliases') is not null
      and to_regclass('public.track_layouts') is not null
      and exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='sessions'
                and column_name='layout_id')),
  -- The table alone is not the promise: text is only deleted at 90 days if the
  -- purge job is scheduled, and a hosted project without pg_cron takes the
  -- table and silently keeps every row. cron.job is read only once pg_cron is
  -- known to be installed, and through query_to_xml, which plans its query at
  -- run time: naming cron.job directly fails the WHOLE audit at parse time on
  -- a database without pg_cron, which no CASE can prevent.
  -- Whether the job has actually RUN is not answerable here: read
  -- cron.job_run_details, or /api/health, which fails ai_text_retention on a
  -- row more than 36 hours past its retain_until, or on an ai_requests preview
  -- still set more than 90 days and 36 hours after its created_at.
  (19, '20260924001700_add_ai_request_text', 'cron job',
      'public.ai_request_text + cron job purge-expired-ai-request-text',
      to_regclass('public.ai_request_text') is not null
      and case when to_regclass('cron.job') is null then false
               else (xpath('count(/table/row)', query_to_xml(
                       'select jobname from cron.job where jobname = ''purge-expired-ai-request-text''',
                       false, false, '')))[1]::text::int > 0
          end),
  -- Only the column default is read, through the catalog: naming the column
  -- fails the whole audit on a database missing 20260924001700. Whether every
  -- existing row was backfilled: select count(*) from public.profiles
  -- where not ai_question_retention_requires_opt_in (0).
  (20, '20260925001800_question_retention_opt_in_for_everyone', 'column default',
      'public.profiles.ai_question_retention_requires_opt_in default true',
      exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='profiles'
                and column_name='ai_question_retention_requires_opt_in'
                and column_default = 'true')),
  (21, '20260926001900_guard_rider_text_capture_at_write', 'trigger',
      'ai_request_text_enforce_keep_rule + ai_requests_enforce_keep_rule',
      (select count(*) from pg_trigger
        where tgname in ('ai_request_text_enforce_keep_rule', 'ai_requests_enforce_keep_rule')
          and not tgisinternal) = 2),
  -- The bucket itself: select public from storage.buckets where id = 'session-photos' (true).
  (22, '20260926002000_add_session_photos', 'column + policies',
      'public.sessions.photo_url + 4 owner-scoped session-photos policies (storage.objects)',
      exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='sessions'
                and column_name='photo_url')
      and (select count(*) from pg_policies p
           join (values
             ('session-photos: select own', 'SELECT', true, false),
             ('session-photos: insert own', 'INSERT', false, true),
             ('session-photos: update own', 'UPDATE', true, true),
             ('session-photos: delete own', 'DELETE', true, false)
           ) as e(policyname, cmd, has_using, has_check) using (policyname)
           where p.schemaname='storage' and p.tablename='objects'
             and p.cmd = e.cmd and p.permissive = 'PERMISSIVE'
             and p.roles = array['authenticated']::name[]
             and p.qual is not distinct from case when e.has_using
               then '((bucket_id = ''session-photos''::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))' end
             and p.with_check is not distinct from case when e.has_check
               then '((bucket_id = ''session-photos''::text) AND ((storage.foldername(name))[1] = (auth.uid())::text))' end) = 4),
  (23, '20260926002100_delete_vehicle_if_sessions_unchanged', 'function',
      'public.delete_vehicle_if_sessions_unchanged(uuid,jsonb)',
      to_regprocedure('public.delete_vehicle_if_sessions_unchanged(uuid,jsonb)') is not null),
  (24, '20260927002000_add_ai_replay_export_view', 'view',
      'public.ai_replay_export',
      to_regclass('public.ai_replay_export') is not null),
  -- The function is create or replace, so an older or hand-edited copy is still
  -- there by name. Only the body fingerprint says the installed definition is
  -- this migration's; the other three read the security and grants it sets.
  -- 20260928002300 replaces the body, so its fingerprint is accepted here too,
  -- as the 1400 row accepts its 1500 replacement.
  (25, '20260927002200_add_create_session_with_laps', 'function',
      'public.create_session_with_laps(uuid,jsonb,jsonb,jsonb)',
      to_regprocedure('public.create_session_with_laps(uuid,jsonb,jsonb,jsonb)') is not null
           and (select md5(p.prosrc) in ('8c9d41c909128fbf696780c5b0c0d5ce', 'd511ff7c7be1ab357c5a1dd207c639ab')
                  and not p.prosecdef
                  and p.proconfig = array['search_path=""']
                  and has_function_privilege('authenticated', p.oid, 'execute')
                  and not has_function_privilege('anon', p.oid, 'execute')
                from pg_proc p where p.oid = to_regprocedure('public.create_session_with_laps(uuid,jsonb,jsonb,jsonb)'))),
  -- Three changes, each read by what makes it true rather than by name: the
  -- create function by its body, the trigger function by its body and its
  -- locked execute, the trigger by its table, timing, event, level and
  -- function (SESSION_TOMBSTONE_TRIGGER_EXACT), the tombstone table by RLS and
  -- its select-only rider grant, and every policy on sessions and
  -- deleted_sessions by its whole tuple, with no other policy on either table
  -- (SESSION_OWNERSHIP_POLICIES_EXACT; permissive policies are OR-ed, so one
  -- more reopens what the five close). All in scripts/build-migration-audit.mjs.
  -- The CASE keeps has_table_privilege off a table that is not there, as in
  -- the 1100 row.
  (26, '20260928002300_session_vehicle_ownership_and_deleted_sessions', 'function + trigger + table + policies',
      'create_session_with_laps cap and tombstones, deleted_sessions, sessions vehicle-owned policies',
      to_regprocedure('public.create_session_with_laps(uuid,jsonb,jsonb,jsonb)') is not null
           and (select md5(p.prosrc) = 'd511ff7c7be1ab357c5a1dd207c639ab'
                from pg_proc p where p.oid = to_regprocedure('public.create_session_with_laps(uuid,jsonb,jsonb,jsonb)'))
           and to_regprocedure('public.record_deleted_session()') is not null
           and (select md5(p.prosrc) = 'f683960a5a0bd7344368cc936e3120b4'
                  and p.prosecdef
                  and p.proconfig = array['search_path=""']
                  and not has_function_privilege('authenticated', p.oid, 'execute')
                  and not has_function_privilege('anon', p.oid, 'execute')
                from pg_proc p where p.oid = to_regprocedure('public.record_deleted_session()'))
           and exists (select 1 from pg_trigger t
                    where t.tgrelid = to_regclass('public.sessions')
                      and t.tgname = 'sessions_record_deleted'
                      and t.tgfoid = to_regprocedure('public.record_deleted_session()')
                      and t.tgtype = 9
                      and t.tgenabled = 'O'
                      and t.tgnargs = 0
                      and t.tgqual is null
                      and not t.tgisinternal)
           and (select count(*) from pg_trigger t
                 where t.tgfoid = to_regprocedure('public.record_deleted_session()')) = 1
           and case when to_regclass('public.deleted_sessions') is null then false
                    else (select c.relrowsecurity from pg_class c where c.oid = to_regclass('public.deleted_sessions'))
                         and has_table_privilege('authenticated', 'public.deleted_sessions', 'select')
                         and not has_table_privilege('authenticated', 'public.deleted_sessions', 'insert, update, delete')
                         and not has_table_privilege('anon', 'public.deleted_sessions', 'select, insert, update, delete')
               end
           and (select count(*) from pg_policies p
                  join (values
                    ('sessions', 'sessions: select own', 'SELECT', '(auth.uid() = user_id)', null),
                    ('sessions', 'sessions: insert own', 'INSERT', null, '7c9b3da91045db80e54e45052117e6e2'),
                    ('sessions', 'sessions: update own', 'UPDATE', '(auth.uid() = user_id)', '7c9b3da91045db80e54e45052117e6e2'),
                    ('sessions', 'sessions: delete own', 'DELETE', '(auth.uid() = user_id)', null),
                    ('deleted_sessions', 'deleted_sessions: select own', 'SELECT', '(auth.uid() = user_id)', null)
                  ) as e(tablename, policyname, cmd, qual, with_check_md5)
                    on e.tablename = p.tablename and e.policyname = p.policyname
                 where p.schemaname = 'public'
                   and p.cmd = e.cmd
                   and p.permissive = 'PERMISSIVE'
                   and p.roles = array['public']::name[]
                   and p.qual is not distinct from e.qual
                   and md5(replace(p.with_check, 'public.vehicles', 'vehicles')) is not distinct from e.with_check_md5) = 5
           and (select count(*) from pg_policies p
                 where p.schemaname = 'public' and p.tablename in ('sessions', 'deleted_sessions')) = 5)
)
select ordinality as "#",
       migration,
       object_kind as kind,
       object_name as "expected object",
       case when present then 'present' else 'MISSING' end as status
from expected
order by ordinality;
