-- GENERATED BY scripts/build-migration-audit.mjs - DO NOT EDIT BY HAND.
-- Regenerate with `npm run db:audit`. The unit suite fails when this file and
-- supabase/migrations/ disagree.
--
-- Which of supabase/migrations/ has this database actually got?
--
-- Read-only. Runs in the Supabase SQL editor against any project, including one
-- that was never built through the CLI and therefore has no
-- `supabase_migrations.schema_migrations` history for `npm run db:status` to
-- read. It asks the schema what is there rather than asking the CLI what it was
-- told, which is the only question that can be answered on this project today
-- (CLAUDE.md, "Database Migrations").
--
-- Each row names one migration and the object that migration is the only thing
-- to create. `present = false` means that migration has not been applied - or was
-- applied and then partially rolled back, which looks the same from here and
-- wants the same investigation.
--
-- WHAT THIS CANNOT TELL YOU: whether PostgREST can SEE what the schema has.
-- A stale schema cache leaves every row below `true` while the Data API answers
-- `PGRST202 Could not find the function ... in the schema cache` - byte-identical
-- to the answer it gives when the function is genuinely absent. If the rows are
-- all `true` and riders still get that error, the cache is the cause: reload it
-- with `notify pgrst, 'reload schema';` (see the runbook entry this ships with).
with expected(ordinality, migration, object_kind, object_name, present) as (values
  (1, '20260223000000_init_baseline_schema', 'table',
      'public.sessions',
      to_regclass('public.sessions') is not null),
  (2, '20260224000000_add_sag_entries', 'table',
      'public.sag_entries',
      to_regclass('public.sag_entries') is not null),
  (3, '20260224000100_add_stripe_profile_fields', 'column',
      'public.profiles.stripe_customer_id',
      exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='profiles'
                and column_name='stripe_customer_id')),
  (4, '20260228000200_add_session_module_metadata', 'column',
      'public.sessions.enabled_modules',
      exists (select 1 from information_schema.columns
              where table_schema='public' and table_name='sessions'
                and column_name='enabled_modules')),
  (5, '20260420000300_add_ai_requests', 'table',
      'public.ai_requests',
      to_regclass('public.ai_requests') is not null),
  (6, '20260422000400_add_adaptive_race_engineer', 'table',
      'public.ai_recommendations',
      to_regclass('public.ai_recommendations') is not null),
  (7, '20260424000500_add_ai_request_observability', 'index',
      'ai_requests_user_fingerprint_created_idx',
      to_regclass('public.ai_requests_user_fingerprint_created_idx') is not null),
  (8, '20260626000600_add_vehicle_baselines', 'table',
      'public.vehicle_baselines',
      to_regclass('public.vehicle_baselines') is not null),
  (9, '20260705000700_add_session_changes', 'table',
      'public.session_changes',
      to_regclass('public.session_changes') is not null),
  -- The reported defect. Nine arguments, in the order the route sends them.
  (10, '20260716000800_add_session_outcomes', 'function',
      'public.save_session_outcome(uuid,uuid,uuid,uuid,text,smallint,text[],text,smallint)',
      to_regprocedure('public.save_session_outcome(uuid,uuid,uuid,uuid,text,smallint,text[],text,smallint)') is not null),
  (11, '20260717000900_add_session_laps', 'table',
      'public.session_laps',
      to_regclass('public.session_laps') is not null),
  (12, '20260718001000_add_beta_foundation', 'table',
      'public.beta_invites',
      to_regclass('public.beta_invites') is not null),
  -- Grants, not objects, so it takes two halves. The insert on sessions is one
  -- this migration is the only thing in the repository to make, and without it
  -- the Data API answers `permission denied for table` on a project created
  -- today - one built before Supabase turned off `auto_expose_new_tables` gets
  -- it from the legacy defaults instead. The revoke is the other half:
  -- `authenticated` must NOT hold update on profiles, because RLS picks the row
  -- and cannot restrict the column, so that privilege is a rider setting their
  -- own `tier`. Testing only the revoke would read `present` on a database that
  -- never granted anything at all.
  --
  -- The CASE is load-bearing rather than style. `has_table_privilege` RAISES on
  -- a table that does not exist, and Postgres does not promise to short-circuit
  -- AND - the docs send you to CASE when evaluation order matters. Without it,
  -- a database missing the baseline aborts this whole query on this row instead
  -- of printing the MISSING rows the operator came here to read, which is
  -- exactly the state the first row exists to report.
  (13, '20260719001100_grant_data_api_access', 'grant',
      'authenticated has insert on public.sessions and NO update on public.profiles',
      case when to_regclass('public.sessions') is null
             or to_regclass('public.profiles') is null then false
           else has_table_privilege('authenticated', 'public.sessions', 'insert')
                and not has_table_privilege('authenticated', 'public.profiles', 'update')
      end),
  (14, '20260816001200_add_profile_on_auth_user_created', 'trigger',
      'on_auth_user_created on auth.users',
      exists (select 1 from pg_trigger
              where tgname='on_auth_user_created'
                and tgrelid='auth.users'::regclass
                and not tgisinternal)),
  (15, '20260824001300_add_vehicle_photos_storage_policies', 'policy',
      'vehicle-photos: insert own (storage.objects)',
      exists (select 1 from pg_policies
              where schemaname='storage' and tablename='objects'
                and policyname='vehicle-photos: insert own')),
  -- 20260901001400 shipped replace_session_laps(...,integer) and 20260903001500
  -- replaced it with (...,jsonb), dropping both earlier signatures. So the
  -- integer form present means 1400 applied and 1500 did not; the jsonb form
  -- present means 1500 applied, which implies 1400 did too.
  (16, '20260901001400_guard_replace_session_laps_against_stale_reads', 'function',
      'public.replace_session_laps(uuid,uuid,jsonb,integer) OR its 1500 replacement',
      to_regprocedure('public.replace_session_laps(uuid,uuid,jsonb,integer)') is not null
      or to_regprocedure('public.replace_session_laps(uuid,uuid,jsonb,jsonb)') is not null),
  (17, '20260903001500_replace_session_laps_compares_lap_content', 'function',
      'public.session_laps_identity(jsonb)',
      to_regprocedure('public.replace_session_laps(uuid,uuid,jsonb,jsonb)') is not null
      and to_regprocedure('public.session_laps_identity(jsonb)') is not null)
)
select ordinality as "#",
       migration,
       object_kind as kind,
       object_name as "expected object",
       case when present then 'present' else 'MISSING' end as status
from expected
order by ordinality;
